### ISSUE TITLE
Proper Content-type header

### ISSUE THREAD

**Issue by a-chernykh** [replay/ngx_http_secure_download#1]
Any chance to get the proper Content-type headers using this type of secure URLs?

Thanks.

**Comment by a-chernykh** [comment]
Ah, I have edited mime.types and it worked. Nevermind.

**Comment by replay** [comment]
cool, add_header might also be a possible solution, similar to what that guy is doing:
http://gogs.info/2010/03/set-filenames-with-nginx-secure-download-module/
